# Generated by Django 4.1.2 on 2022-12-10 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaardb',
            name='Mobile',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='aadhaardb',
            name='AadhaarNum',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
