# Generated by Django 4.1.2 on 2022-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0002_aadhaardb_mobile_alter_aadhaardb_aadhaarnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardb',
            name='Age',
            field=models.IntegerField(default=None),
        ),
    ]
